// maximum of certifications to show
export const certificationsShowMax = 3;
// certifications
export const certifications = [
  {
    title: "CS50x - Introduction to Computer Science",
    status: 0,
    expandable: 1,
    school: 1,
    link: "https://pll.harvard.edu/course/cs50-introduction-computer-science",
    certification:
      "https://certificates.cs50.io/29dbe20a-aaab-4cc0-8d03-9c9bb90acce2.png?size=letter",
    place: "Harvard",
    type: "Online Course",
    startDate: "2023/09/01",
    endDate: "2023/12/31",
    desc:
      "Acquire a strong foundation in computer science, programming, and key concepts. Gain proficiency in languages like C, Python, SQL, JavaScript, CSS, and HTML.",
    topics: [
      "A broad and robust understanding of computer science and programming",
      "How to think algorithmically and solve programming problems efficiently",
      "Concepts like abstraction, algorithms, data structures, encapsulation, resource management, security, software engineering, and web development",
      "Familiarity with a number of languages, including C, Python, SQL, and JavaScript plus CSS and HTML",
      "How to engage with a vibrant community of like-minded learners from all levels of experience",
      "How to develop and present a final programming project to your peers",
    ],
    tags: [
      "Computer Science",
      "Data Structures",
      "Algorithms",
      "C",
      "Python",
      "SQL",
      "HTML",
      "CSS",
      "Javascript",
    ],
  },
  {
    title: "Interactivity and Design",
    status: 1,
    expandable: 1,
    school: 0,
    link: "",
    certification: "",
    place: "OsloMet",
    type: "Campus",
    startDate: "2024/01/01",
    endDate: "2024/06/30",
    desc: "",
    topics: [],
    tags: [],
  },

  {
    title: "The Odin Project",
    status: 1,
    expandable: 1,
    school: 0,
    link: "https://www.theodinproject.com/",
    certification: "",
    place: "Erik Trautman",
    type: "Online Course",
    startDate: "2024/01/01",
    endDate: "2024/12/31",
    desc:
      "The Odin Project is an open-source curriculum for learning web development. It provides free, high-quality resources and a supportive community for self-learners.",
    topics: [
      "HTML",
      "CSS",
      "JavaScript",
      "Node.js",
      "Express.js",
      "React",
      "Databases",
      "Git",
      "GitHub",
      "Responsive Design",
    ],
    tags: [
      "Web Development",
      "HTML",
      "CSS",
      "JavaScript",
      "Node.js",
      "React",
      "Git",
      "GitHub",
    ],
  },
  {
    title: "AWS Cloud Practitioner Certificate",
    status: 2,
    expandable: 1,
    school: 1,
    link: "https://aws.amazon.com/certification/certified-cloud-practitioner/",
    certification: "",
    place: "Amazon",
    type: "Online Course",
    startDate: "",
    endDate: "",
    desc:
      "Acquire a strong foundation in computer science, programming, and key concepts. Gain proficiency in languages like C, Python, SQL, JavaScript, CSS, and HTML.",

    topics: [
      "An understanding of AWS Cloud concepts",
      "Essential AWS services, their use cases, and basic architecture best practices",
      "AWS Cloud value proposition",
      "The AWS Cloud's shared responsibility model",
      "Key security and compliance concepts",
      "Basic familiarity with AWS pricing, billing, and account structures",
    ],
    tags: [
      "AWS",
      "Cloud Computing",
      "AWS Cloud Concepts",
      "AWS Services",
      "Security and Compliance",
    ],
  },

  /*
  {
    title: "Harvard CS50p - Introduction to Programming with Python", status: 2,
    expandable: true,
    link: "https://pll.harvard.edu/course/cs50s-introduction-programming-python",
    certification: "",
    topics: [
      "In-depth understanding of Python programming",
      "Working with functions, arguments, and return values",
      "Handling variables, data types, and exceptions",
      "Understanding conditionals and Boolean expressions",
      "Mastering loops for efficient programming",
      "Exploring objects, methods, and object-oriented programming concepts",
      "Dealing with file I/O and using various libraries",
    ],
    tags: ["Computer Science", "Information Technology", "Databases", "Python"],
  },
  */
  {
    title: "Google UX Design Certificate",
    status: 2,
    expandable: 1,
    school: 1,
    link: "https://grow.google/certificates/ux-design/",
    certification: "",
    place: "Google",
    type: "Online Course",
    startDate: "",
    endDate: "",
    desc:
      "Acquire a strong foundation in computer science, programming, and key concepts. Gain proficiency in languages like C, Python, SQL, JavaScript, CSS, and HTML.",

    topics: [
      "Comprehensive understanding of User Experience (UX) Design principles",
      "Applying UX design techniques to create user-friendly digital products",
      "Design thinking and problem-solving strategies",
      "Prototyping and usability testing",
      "UI (User Interface) design principles",
      "Creating wireframes and interactive prototypes",
      "Real-world project experience",
    ],
    tags: [
      "User Experience Design",
      "UX/UI Design",
      "Prototyping",
      "Design Thinking",
      "Google Certification",
    ],
  },
  {
    title: "Google Cloud Certification",
    status: 2,
    expandable: 1,
    school: 1,
    link: "https://cloud.google.com/learn/certification?hl=nb",
    certification: "",
    place: "Google",
    type: "Online Course",
    startDate: "",
    endDate: "",
    desc:
      "Acquire a strong foundation in computer science, programming, and key concepts. Gain proficiency in languages like C, Python, SQL, JavaScript, CSS, and HTML.",

    topics: [
      "Understanding Google Cloud services and solutions",
      "Creating and managing virtual machine instances",
      "Cloud storage and data storage options",
      "Scalability and load balancing",
      "Cloud identity and access management",
      "Google Cloud networking concepts",
    ],
    tags: [
      "Cloud Computing",
      "Google Cloud",
      "Virtual Machines",
      "Data Storage",
      "Networking",
    ],
  },
  {
    title: "Google Project Management Certificate",
    status: 2,
    expandable: 1,
    school: 1,
    link: "https://grow.google/certificates/project-management/",
    certification: "",
    place: "Google",
    type: "Online Course",
    startDate: "",
    endDate: "",
    desc:
      "Acquire a strong foundation in computer science, programming, and key concepts. Gain proficiency in languages like C, Python, SQL, JavaScript, CSS, and HTML.",

    topics: [
      "Effective project management and leadership skills",
      "Scope, time, cost, quality, human resources, and risk management",
      "Agile project management methodologies",
      "Collaborative project planning and execution",
      "Hands-on experience with real-world projects",
      "Tools and techniques for project management",
    ],
    tags: [
      "Project Management",
      "Leadership",
      "Agile Methodologies",
      "Collaborative Planning",
      "Google Certification",
    ],
  },

  {
    title: "Linux Professional Institute LPIC-1",
    status: 2,
    expandable: 1,
    school: 1,
    link: "https://www.lpi.org/our-certifications/lpic-1-overview/",
    certification: "",
    place: "Linux",
    type: "Online Course",
    startDate: "",
    endDate: "",
    desc:
      "Acquire a strong foundation in computer science, programming, and key concepts. Gain proficiency in languages like C, Python, SQL, JavaScript, CSS, and HTML.",

    topics: [
      "Linux installation and package management",
      "GNU and Unix commands",
      "Devices, Linux filesystems, and filesystem hierarchy standard",
      "System boot and initialization",
      "Shells, scripting, and data management",
      "User interfaces and desktops",
      "Administrative tasks",
    ],
    tags: [
      "Linux",
      "LPIC-1",
      "GNU",
      "Unix",
      "Package Management",
      "Filesystems",
      "Boot Process",
      "Shell Scripting",
      "Desktop Environment",
    ],
  },
];
